### ISSUE TITLE
Gym Environment and using stable baselines

### ISSUE THREAD

**Issue by anirjoshi** [aidudezzz/deepbots#151]
I would like to use Webots along with [stable baselines](https://stable-baselines3.readthedocs.io/en/master/). Is that possible to do using deepbots?

**Comment by KelvinYang0320** [comment]
@anirjoshi Thank you for opening the issue.
We have some stable-baseline examples in our deepworlds. 😄
https://github.com/aidudezzz/deepworlds/tree/dev/examples/cartpole#discrete-action-space

**Comment by anirjoshi** [comment]
Thank you for the quick response!
